<?php
/**
 * @file
 * This module provides a node type called semestarx
 */ 
/**
 * Implements hook_node_info() to provide our semestarx type.
 */
function semestarx_node_info() {
 return array(
 'semestarx' => array(
 'name' => t('semestarx'),
 'base' => 'semestarx',
 'description' => t('Use this content type to create semestar.'),
 'has_title' => TRUE,
 'title_label' => t('Naziv semestara'),
 'help' => t('Unesi podatke o semestaru'),
 ),
 );
} 

function semestarx_insert($node) {
// log details of the job posting to watchdog
watchdog('semestarx', 'Novi semestar sa nazivom: '.$node->title.
' je dodan by UID: '.$node->uid, $variables = array(),
WATCHDOG_NOTICE, $link = 'node/'.$node->nid);
}

/**
 * Implements hook_theme_registry_alter().
 */
function semestarx_theme_registry_alter(&$theme_registry) {
    // Defined path to the current module.
    $module_path = drupal_get_path('module', 'semestarx');
    // Find all .tpl.php files in this module's folder recursively.
    $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
    // Iterate through all found template file objects.
    foreach ($template_file_objects as $key => $template_file_object) {
        // If the template has not already been overridden by a theme.
        if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
            // Alter the theme path and template elements.
            $theme_registry[$key]['theme path'] = $module_path;
            $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
            $theme_registry[$key]['type'] = 'module';
        }
    }
}
function daj_predmete($trenutni_link){
    $odsjeci=menu_tree_all_data('menu-sidebar1');
    foreach ($odsjeci as $odsjek) {
        foreach ($odsjek['below'] as $semestar) {
            if($semestar['link']['link_path']==$trenutni_link) return $semestar['below'];
        }
    }
}
function semestarx_node_view($node,$view_mode){
    if($node->type=='semestarx'){
    $predmeti = daj_predmete(current_path());
    //$meni=$meni['sidebar1'];
    $dodani='<table class="predmeti_sem">'.
                '<tr>'.
                    '<th> Naziv predmeta </th>'.
                    '<th> Predmetni nastavnik </th>'.
                    '<th> Predavanja </th>'.
                    '<th> Vježbe </th>'.
                    '<th> Tutoriali </th>'.
                    '<th> ECTS </th>'.
                '</tr>'
            ;
    $izborni=$dodani;
    foreach ($predmeti as $predmet ) {
        $privremeni='<tr>';
        $cur_node=menu_get_object('node',1,$predmet['link']['link_path']);
        $naziv_pred = htmlspecialchars ( array_values($cur_node->predmet_naziv)[0][0]['value']);
        $predavanja_pred = htmlspecialchars ( array_values($cur_node->predmet_predavanja)[0][0]['value']);
        $vjezbe_pred = htmlspecialchars ( array_values($cur_node->predmet_vjezbe)[0][0]['value']);
        $tutoriali_pred = htmlspecialchars ( array_values($cur_node->predmet_tutoriali)[0][0]['value']);
        $nastavnik_pred = htmlspecialchars ( array_values($cur_node->predmet_nastavnik)[0][0]['value']);
        $bodovi_pred = htmlspecialchars ( array_values($cur_node->predmet_bodovi)[0][0]['value']);
        //drupal_set_message(print_r($cur_node));
        $izborniTF =  array_values($cur_node->predmet_izborni)[0][0]['value'];
        $privremeni=$privremeni.'<td><a href=/'.$predmet['link']['link_path'].'>'.$naziv_pred.'</a></td>'.
                        '<td>'.$nastavnik_pred.'</td>'.
                        '<td>'.$predavanja_pred.'</td>'.
                        '<td>'.$vjezbe_pred.'</td>'.
                        '<td>'.$tutoriali_pred.'</td>'.
                        '<td>'.$bodovi_pred.'</td>';
        $privremeni=$privremeni.'</tr>';
        if($izborniTF==0){
            $izborni=$izborni.$privremeni;
        }
        else
        {
            $dodani=$dodani.$privremeni;
        }
    }
    $dodani=$dodani.'</table>';
    $izborni=$izborni.'</table>';
    $node->content['redovni_predmeti']=array(
                 "#markup"=> $dodani,
                 "#weight"=> 100
              );
    $node->content['izborni_predmeti']=array(
                "#markup"=> $izborni,
                "#weight"=> 100
              );   
    }
}