<?php
/**
 * @file
 * This module provides a node type called predmet
 */ 
/**
 * Implements hook_node_info() to provide our predmet type.
 */
function predmet_node_info() {
 return array(
 'predmet' => array(
 'name' => t('predmet'),
 'base' => 'predmet',
 'description' => t('Use this content type to create predmet.'),
 'has_title' => TRUE,
 'title_label' => t('Naziv predmeta'),
 'help' => t('Unesi podatke o predmetu'),
 ),
 );
} 

function predmet_insert($node) {
// log details of the job posting to watchdog
watchdog('predmet', 'Novi predmet sa nazivom: '.$node->title.
' je dodan by UID: '.$node->uid, $variables = array(),
WATCHDOG_NOTICE, $link = 'node/'.$node->nid);
}

/**
 * Implements hook_theme_registry_alter().
 */
function predmet_theme_registry_alter(&$theme_registry) {
    // Defined path to the current module.
    $module_path = drupal_get_path('module', 'predmet');
    // Find all .tpl.php files in this module's folder recursively.
    $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
    // Iterate through all found template file objects.
    foreach ($template_file_objects as $key => $template_file_object) {
        // If the template has not already been overridden by a theme.
        if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
            // Alter the theme path and template elements.
            $theme_registry[$key]['theme path'] = $module_path;
            $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
            $theme_registry[$key]['type'] = 'module';
        }
    }
}