<?php
function rmeni_block_info(){
	$block['rmeni'] = array(
 	'info' => t('Meni'),
 	'cache' => DRUPAL_NO_CACHE, );
  	return $block; 
}
function rmeni_block_view($block_key){
	$block = array();
	if($block_key == 'rmeni'){ 
	//We only want to define the content of OUR block 
	//This is the title of the block. 
	$block['content']=t('bjazi');
	} 
	return $block; 
}
/**
 * Implements hook_theme_registry_alter().
 */
function rmeni_theme_registry_alter(&$theme_registry) {
    // Defined path to the current module.
    $module_path = drupal_get_path('module', 'rmeni');
    // Find all .tpl.php files in this module's folder recursively.
    $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
    drupal_set_message(print_r($template_file_objects));
    // Iterate through all found template file objects.
    foreach ($template_file_objects as $key => $template_file_object) {
        // If the template has not already been overridden by a theme.
        if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
            // Alter the theme path and template elements.
            $theme_registry[$key]['theme path'] = $module_path;
            $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
            $theme_registry[$key]['type'] = 'module';
        }
    }
}